### ISSUE TITLE
this tool counting item is zero and it not scraping any thing

### ISSUE THREAD

**Issue by AsifJawad024** [LeadGenerationTools/google-maps-extractor#1]
This tool is not scraping any items from the map. I am searching for "Salon de coiffure" and then clicking the "Start Auto Extract" button. The tool scrolls down the entire sidebar as expected, but it still shows zero items scraped, even though there are more than 50 items available. It was working fine a few days ago, but today it’s facing this issue. I even tried cloning it again, but the problem persists. 

Could you help me identify the issue?

**Comment by LeadGenerationTools** [comment]
Fixed.
